### ISSUE TITLE
can't find variable

### ISSUE THREAD

**Issue by Nichloya** [flamewing/asl-releases#27]
![photo_2023-02-12_11-26-42](https://user-images.githubusercontent.com/108447847/218300765-efc5638e-b99e-49d3-bcef-6aed8affbd03.jpg)
![photo_2023-02-12_11-26-45](https://user-images.githubusercontent.com/108447847/218300767-33a4552e-25b4-4f46-b6d6-eb720a1f3cb9.jpg)

**Comment by Clownacy** [comment]
It can find the variable, it's just that it can't be used in short addressing mode: it needs to be changed from `(Play_Music).w` to `(Play_Music).l`.
